name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # once a day
  workflow_dispatch:      # manual run button
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: soham1105-tech
          outputs: |
            dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/snake.svg"
          message: "chore: update snake animation"
